export const memberList = [
  {
    status: 'A',
    membershipNumber: '1002',
    firstName: 'James',
    lastName: 'Pirhonen',
  },
  {
    status: 'A',
    membershipNumber: '1004',
    firstName: 'Ian W.',
    lastName: 'Trumpour',
  },
  {
    status: 'A',
    membershipNumber: '1006',
    firstName: 'Andrew',
    lastName: 'Weeber',
  },
  {
    status: 'A',
    membershipNumber: '1008',
    firstName: 'Matthias',
    lastName: 'Becker',
  },
  {
    status: 'A',
    membershipNumber: '1009',
    firstName: 'Thomas',
    lastName: 'Berleth',
  },
  {
    status: 'A',
    membershipNumber: '1011',
    firstName: 'Hans',
    lastName: 'Paabor',
  },
  {
    status: 'A',
    membershipNumber: '1013',
    firstName: 'George',
    lastName: 'Morrison',
  },
  {
    status: 'A',
    membershipNumber: '1014',
    firstName: 'Ronald J.',
    lastName: 'Smit',
  },
  {
    status: 'A',
    membershipNumber: '1015',
    firstName: 'Kat',
    lastName: 'Perez',
  },
  {
    status: 'A',
    membershipNumber: '1016',
    firstName: 'Richard',
    lastName: 'Snider',
  },
  {
    status: 'A',
    membershipNumber: '1017',
    firstName: 'Michael',
    lastName: 'Fong',
  },
  {
    status: 'A',
    membershipNumber: '1021',
    firstName: 'Kate',
    lastName: 'Wilson',
  },
  {
    status: 'A',
    membershipNumber: '1024',
    firstName: 'Kate',
    lastName: 'George',
  },
  {
    status: 'A',
    membershipNumber: '1025',
    firstName: 'J.Eduardo',
    lastName: 'Pereira',
  },
  {
    status: 'A',
    membershipNumber: '1026',
    firstName: 'Kean P.',
    lastName: 'Moynihan',
  },
  {
    status: 'A',
    membershipNumber: '1027',
    firstName: 'Rufus',
    lastName: 'Wilkes',
  },
  {
    status: 'A',
    membershipNumber: '1028',
    firstName: 'Edward R.',
    lastName: 'Snoyer',
  },
  {
    status: 'A',
    membershipNumber: '1031',
    firstName: 'Marc',
    lastName: 'Davies',
  },
  {
    status: 'A',
    membershipNumber: '1033',
    firstName: 'Scott',
    lastName: 'Jones',
  },
  {
    status: 'A',
    membershipNumber: '1035',
    firstName: 'Tim',
    lastName: 'Kirkwood',
  },
  {
    status: 'A',
    membershipNumber: '1037',
    firstName: 'Alison',
    lastName: 'Barlow',
  },
  {
    status: 'A',
    membershipNumber: '1043',
    firstName: 'Marcus',
    lastName: 'Van Ierssel',
  },
  {
    status: 'A',
    membershipNumber: '1044',
    firstName: 'Frederick',
    lastName: 'Kent',
  },
  {
    status: 'A',
    membershipNumber: '1045',
    firstName: 'Chris',
    lastName: 'Speed',
  },
  {
    status: 'A',
    membershipNumber: '1046',
    firstName: 'Bjorn',
    lastName: 'Pettersson',
  },
  {
    status: 'A',
    membershipNumber: '1047',
    firstName: 'Adam',
    lastName: 'Walkowiak',
  },
  {
    status: 'A',
    membershipNumber: '1048',
    firstName: 'Keith',
    lastName: 'Bohlender',
  },
  {
    status: 'A',
    membershipNumber: '1053',
    firstName: 'Barna',
    lastName: 'Moricz',
  },
  {
    status: 'A',
    membershipNumber: '1054',
    firstName: 'Robert',
    lastName: 'Hickman',
  },
  {
    status: 'A',
    membershipNumber: '1057',
    firstName: 'Rafal',
    lastName: 'Bilyk',
  },
  {
    status: 'A',
    membershipNumber: '1060',
    firstName: 'Harry',
    lastName: 'Minaker',
  },
  {
    status: 'A',
    membershipNumber: '1070',
    firstName: 'Cathryn',
    lastName: 'MacFarlane',
  },
  {
    status: 'A',
    membershipNumber: '1071',
    firstName: 'Boris Alexandre',
    lastName: 'Sucharov',
  },
  {
    status: 'A',
    membershipNumber: '1074',
    firstName: 'Alexei',
    lastName: 'Pachkevitch',
  },
  {
    status: 'A',
    membershipNumber: '1077',
    firstName: 'Jeff',
    lastName: 'Willis',
  },
  {
    status: 'A',
    membershipNumber: '1078',
    firstName: 'Dominik',
    lastName: 'Gawron',
  },
  {
    status: 'A',
    membershipNumber: '1082',
    firstName: 'Timon',
    lastName: 'Orawski',
  },
  {
    status: 'A',
    membershipNumber: '1083',
    firstName: 'Brian',
    lastName: 'Burchell',
  },
  {
    status: 'A',
    membershipNumber: '1085',
    firstName: 'Gregory',
    lastName: 'Graham',
  },
  {
    status: 'A',
    membershipNumber: '1087',
    firstName: 'John K.',
    lastName: 'Hunter',
  },
  {
    status: 'A',
    membershipNumber: '1090',
    firstName: 'James',
    lastName: 'Roscoe',
  },
  {
    status: 'A',
    membershipNumber: '1092',
    firstName: 'John',
    lastName: 'Ross',
  },
  {
    status: 'A',
    membershipNumber: '1094',
    firstName: 'Tom',
    lastName: 'Majcherczyk',
  },
  {
    status: 'A',
    membershipNumber: '1095',
    firstName: 'Mike',
    lastName: 'Rossiter',
  },
  {
    status: 'A',
    membershipNumber: '1096',
    firstName: 'John',
    lastName: 'Komac',
  },
  {
    status: 'A',
    membershipNumber: '1098',
    firstName: 'Brian',
    lastName: 'Lumley',
  },
  {
    status: 'A',
    membershipNumber: '1099',
    firstName: 'Jason',
    lastName: 'Kahng',
  },
  {
    status: 'A',
    membershipNumber: '1100',
    firstName: 'Slawomir (Slav)',
    lastName: 'Domurat',
  },
  {
    status: 'A',
    membershipNumber: '1115',
    firstName: 'John',
    lastName: 'Yi Gong',
  },
  {
    status: 'A',
    membershipNumber: '1117',
    firstName: 'Jack',
    lastName: 'Willoughby',
  },
  {
    status: 'A',
    membershipNumber: '1118',
    firstName: 'Mike',
    lastName: 'Chmura',
  },
  {
    status: 'A',
    membershipNumber: '1120',
    firstName: 'Michelle',
    lastName: 'Robidoux',
  },
  {
    status: 'A',
    membershipNumber: '1121',
    firstName: 'Peter',
    lastName: 'Weninger',
  },
  {
    status: 'A',
    membershipNumber: '1122',
    firstName: 'Jeffrey',
    lastName: 'James',
  },
  {
    status: 'A',
    membershipNumber: '1123',
    firstName: 'Graham',
    lastName: 'Reid',
  },
  {
    status: 'A',
    membershipNumber: '1124',
    firstName: 'Vincent',
    lastName: 'Grossi',
  },
  {
    status: 'A',
    membershipNumber: '1125',
    firstName: 'Jaime',
    lastName: 'Restrepo',
  },
  {
    status: 'A',
    membershipNumber: '1127',
    firstName: 'Mark',
    lastName: 'Lewiecki',
  },
  {
    status: 'A',
    membershipNumber: '1128',
    firstName: 'Nicholas',
    lastName: 'Scribner',
  },
  {
    status: 'A',
    membershipNumber: '1135',
    firstName: 'Antonio',
    lastName: 'Rebelo',
  },
  {
    status: 'A',
    membershipNumber: '1136',
    firstName: 'Michael',
    lastName: 'Wilson',
  },
  {
    status: 'A',
    membershipNumber: '1137',
    firstName: 'Katie',
    lastName: 'Grundy',
  },
  {
    status: 'A',
    membershipNumber: '1138',
    firstName: 'Frederic',
    lastName: 'Chevalier',
  },
  {
    status: 'A',
    membershipNumber: '1140',
    firstName: 'Carol',
    lastName: 'McFarlane',
  },
  {
    status: 'A',
    membershipNumber: '1141',
    firstName: 'Janaya',
    lastName: 'Letkeman',
  },
  {
    status: 'A',
    membershipNumber: '1142',
    firstName: 'Mike',
    lastName: 'McIntyre',
  },
  {
    status: 'A',
    membershipNumber: '1143',
    firstName: 'Graham',
    lastName: 'Merry',
  },
  {
    status: 'A',
    membershipNumber: '1144',
    firstName: 'Daniel ',
    lastName: 'Mingorance-Geraldo',
  },
  {
    status: 'A',
    membershipNumber: '1145',
    firstName: 'Marc ',
    lastName: 'Grossi',
  },
  {
    status: 'A',
    membershipNumber: '1146',
    firstName: 'Daniel ',
    lastName: 'Aufgang',
  },
  {
    status: 'A',
    membershipNumber: '1148',
    firstName: 'Soren',
    lastName: 'Hess',
  },
  {
    status: 'A',
    membershipNumber: '1149',
    firstName: 'John ',
    lastName: 'Gunel',
  },
  {
    status: 'A',
    membershipNumber: '1150',
    firstName: 'Andrew',
    lastName: 'White',
  },
  {
    status: 'A',
    membershipNumber: '1151',
    firstName: 'Adam',
    lastName: 'Melanson',
  },
  {
    status: 'A',
    membershipNumber: '1152',
    firstName: 'Yu Charlie',
    lastName: 'Yang',
  },
  {
    status: 'A',
    membershipNumber: '1153',
    firstName: 'Bill',
    lastName: 'Hutton',
  },
  {
    status: 'A',
    membershipNumber: '1154',
    firstName: 'Eileen',
    lastName: 'Taylor',
  },
  {
    status: 'A',
    membershipNumber: '1155',
    firstName: 'Dominic',
    lastName: 'Ewenson',
  },
  {
    status: 'A',
    membershipNumber: '1156',
    firstName: 'Brian',
    lastName: 'Cooper',
  },
  {
    status: 'A',
    membershipNumber: '1157',
    firstName: 'Alex',
    lastName: 'Bartlett',
  },
  {
    status: 'B',
    membershipNumber: '1006',
    firstName: 'Brenda',
    lastName: 'Nowitski',
  },
  {
    status: 'B',
    membershipNumber: '1007',
    firstName: 'Valerie',
    lastName: 'Schofield',
  },
  {
    status: 'B',
    membershipNumber: '1008',
    firstName: 'Andres',
    lastName: 'Pang-Becker',
  },
  {
    status: 'B',
    membershipNumber: '1011',
    firstName: 'Carol',
    lastName: 'Paabor',
  },
  {
    status: 'B',
    membershipNumber: '1014',
    firstName: 'Sue',
    lastName: 'Smit',
  },
  {
    status: 'B',
    membershipNumber: '1015',
    firstName: 'Claudio',
    lastName: 'Zamora',
  },
  {
    status: 'B',
    membershipNumber: '1016',
    firstName: 'Laura',
    lastName: 'Snider',
  },
  {
    status: 'B',
    membershipNumber: '1017',
    firstName: 'Susy',
    lastName: 'Fong',
  },
  {
    status: 'B',
    membershipNumber: '1021',
    firstName: 'Don',
    lastName: 'Vermeer',
  },
  {
    status: 'B',
    membershipNumber: '1025',
    firstName: 'Marc',
    lastName: 'Feifer',
  },
  {
    status: 'B',
    membershipNumber: '1026',
    firstName: 'William',
    lastName: 'Moynihan',
  },
  {
    status: 'B',
    membershipNumber: '1028',
    firstName: 'Ros-Marie',
    lastName: 'Snoyer',
  },
  {
    status: 'B',
    membershipNumber: '1033',
    firstName: 'Heather',
    lastName: 'Jones',
  },
  {
    status: 'B',
    membershipNumber: '1035',
    firstName: 'Valentia',
    lastName: 'Kirkwood',
  },
  {
    status: 'B',
    membershipNumber: '1037',
    firstName: 'John',
    lastName: 'Toews',
  },
  {
    status: 'B',
    membershipNumber: '1043',
    firstName: 'Jennifer',
    lastName: 'van Ierrssel',
  },
  {
    status: 'B',
    membershipNumber: '1044',
    firstName: 'Celina',
    lastName: 'Grebski',
  },
  {
    status: 'B',
    membershipNumber: '1045',
    firstName: 'Pamela',
    lastName: 'Speed',
  },
  {
    status: 'B',
    membershipNumber: '1047',
    firstName: 'Marzena',
    lastName: 'Walkowiak',
  },
  {
    status: 'B',
    membershipNumber: '1048',
    firstName: 'Marie',
    lastName: 'Gallo-Bohlender',
  },
  {
    status: 'B',
    membershipNumber: '1053',
    firstName: 'Audrey',
    lastName: 'Lupke',
  },
  {
    status: 'B',
    membershipNumber: '1054',
    firstName: 'Beth',
    lastName: 'Hickman',
  },
  {
    status: 'B',
    membershipNumber: '1055',
    firstName: 'Ejay',
    lastName: 'Russel',
  },
  {
    status: 'B',
    membershipNumber: '1057',
    firstName: 'Paulina',
    lastName: 'Brozyna',
  },
  {
    status: 'B',
    membershipNumber: '1069',
    firstName: 'Margaret',
    lastName: 'Hussar',
  },
  {
    status: 'B',
    membershipNumber: '1070',
    firstName: 'Paul',
    lastName: 'Scott',
  },
  {
    status: 'B',
    membershipNumber: '1071',
    firstName: 'Luciana',
    lastName: 'Pache de Faria',
  },
  {
    status: 'B',
    membershipNumber: '1073',
    firstName: 'Carol',
    lastName: 'Wilson',
  },
  {
    status: 'B',
    membershipNumber: '1074',
    firstName: 'Elena',
    lastName: 'Pachkevitch',
  },
  {
    status: 'B',
    membershipNumber: '1077',
    firstName: 'Gabriele',
    lastName: 'Muekusch',
  },
  {
    status: 'B',
    membershipNumber: '1082',
    firstName: 'Sonia',
    lastName: 'Satov',
  },
  {
    status: 'B',
    membershipNumber: '1083',
    firstName: 'Lisa',
    lastName: 'Lomax',
  },
  {
    status: 'B',
    membershipNumber: '1085',
    firstName: 'Judith',
    lastName: 'MacDonald',
  },
  {
    status: 'B',
    membershipNumber: '1087',
    firstName: 'Lois',
    lastName: 'Hunter',
  },
  {
    status: 'B',
    membershipNumber: '1090',
    firstName: 'Melanie',
    lastName: 'Roscoe',
  },
  {
    status: 'B',
    membershipNumber: '1091',
    firstName: 'Ellie',
    lastName: 'Myers',
  },
  {
    status: 'B',
    membershipNumber: '1092',
    firstName: 'Maia',
    lastName: 'Onno',
  },
  {
    status: 'B',
    membershipNumber: '1093',
    firstName: 'Petr',
    lastName: 'Jano',
  },
  {
    status: 'B',
    membershipNumber: '1094',
    firstName: 'Cristina',
    lastName: 'Delago',
  },
  {
    status: 'B',
    membershipNumber: '1095',
    firstName: 'Lauren',
    lastName: 'Dixon',
  },
  {
    status: 'B',
    membershipNumber: '1100',
    firstName: 'Stephanie',
    lastName: 'Domurat',
  },
  {
    status: 'B',
    membershipNumber: '1104',
    firstName: 'Darragh',
    lastName: 'Purcell',
  },
  {
    status: 'B',
    membershipNumber: '1105',
    firstName: 'Frances (Nicki)',
    lastName: 'Anger',
  },
  {
    status: 'B',
    membershipNumber: '1108',
    firstName: 'Lydia',
    lastName: 'Gilbert',
  },
  {
    status: 'B',
    membershipNumber: '1114',
    firstName: 'Yulia',
    lastName: 'Lachakov',
  },
  {
    status: 'B',
    membershipNumber: '1118',
    firstName: 'Beata',
    lastName: 'Szwoger-Lettecki',
  },
  {
    status: 'B',
    membershipNumber: '1120',
    firstName: 'Christine',
    lastName: 'Beckerman',
  },
  {
    status: 'B',
    membershipNumber: '1122',
    firstName: 'Kate',
    lastName: 'McCormick',
  },
  {
    status: 'B',
    membershipNumber: '1127',
    firstName: 'Sophia',
    lastName: 'Lilly',
  },
  {
    status: 'B',
    membershipNumber: '1128',
    firstName: 'Katalin',
    lastName: 'Ruza',
  },
  {
    status: 'B',
    membershipNumber: '1129',
    firstName: 'Jean',
    lastName: 'Wright',
  },
  {
    status: 'B',
    membershipNumber: '1135',
    firstName: 'Grace',
    lastName: 'Rebelo',
  },
  {
    status: 'B',
    membershipNumber: '1136',
    firstName: 'Meghan',
    lastName: 'Siddall',
  },
  {
    status: 'B',
    membershipNumber: '1138',
    firstName: 'Isabelle',
    lastName: 'Poirier',
  },
  {
    status: 'B',
    membershipNumber: '1139',
    firstName: 'James',
    lastName: 'Sutcliffe',
  },
  {
    status: 'B',
    membershipNumber: '1141',
    firstName: 'Robert ',
    lastName: 'Froese',
  },
  {
    status: 'B',
    membershipNumber: '1142',
    firstName: 'Alison',
    lastName: 'McIntyre',
  },
  {
    status: 'B',
    membershipNumber: '1143',
    firstName: 'Christine',
    lastName: 'Lee',
  },
  {
    status: 'C',
    membershipNumber: '1129',
    firstName: 'Jaan',
    lastName: 'Luts',
  },
  {
    status: 'C',
    membershipNumber: '1130',
    firstName: 'Carole',
    lastName: 'Enriquez',
  },
  {
    status: 'C',
    membershipNumber: '1133',
    firstName: 'Anna',
    lastName: 'Pachkevitch',
  },
  {
    status: 'C',
    membershipNumber: '1139',
    firstName: 'Katina',
    lastName: 'Sutcliffe',
  },
  {
    status: 'C',
    membershipNumber: '1147',
    firstName: 'Joel',
    lastName: 'Aufgang',
  },
];
