export const memberList = [
	{
		status: "A",
		membershipNumber: "1002",
		firstName: "James",
		lastName: "Pirhonen",
	},
	{
		status: "A",
		membershipNumber: "1004",
		firstName: "Ian W.",
		lastName: "Trumpour",
	},
	{
		status: "A",
		membershipNumber: "1006",
		firstName: "Andrew",
		lastName: "Weeber",
	},
	{
		status: "B",
		membershipNumber: "1006",
		firstName: "Brenda",
		lastName: "Nowitski",
	},
	{
		status: "B",
		membershipNumber: "1007",
		firstName: "Valerie",
		lastName: "Schofield",
	},
	{
		status: "E",
		membershipNumber: "1007",
		firstName: "Barrie",
		lastName: "Farrell",
	},
	{
		status: "B",
		membershipNumber: "1008",
		firstName: "Andres",
		lastName: "Pang-Becker",
	},
	{
		status: "D",
		membershipNumber: "1008",
		firstName: "Matthias",
		lastName: "Becker",
	},
	{
		status: "A",
		membershipNumber: "1009",
		firstName: "Thomas",
		lastName: "Berleth",
	},
	{
		status: "E",
		membershipNumber: "1010",
		firstName: "John",
		lastName: "Morra",
	},
	{
		status: "B",
		membershipNumber: "1011",
		firstName: "Carol",
		lastName: "Paabor",
	},
	{
		status: "A",
		membershipNumber: "1013",
		firstName: "George",
		lastName: "Morrison",
	},
	{
		status: "A",
		membershipNumber: "1014",
		firstName: "Ronald J.",
		lastName: "Smit",
	},
	{
		status: "B",
		membershipNumber: "1014",
		firstName: "Sue",
		lastName: "Smit",
	},
	{
		status: "B",
		membershipNumber: "1015",
		firstName: "Claudio",
		lastName: "Zamora",
	},
	{
		status: "A",
		membershipNumber: "1016",
		firstName: "Richard",
		lastName: "Snider",
	},
	{
		status: "B",
		membershipNumber: "1016",
		firstName: "Laura",
		lastName: "Snider",
	},
	{
		status: "A",
		membershipNumber: "1017",
		firstName: "Michael",
		lastName: "Fong",
	},
	{
		status: "B",
		membershipNumber: "1017",
		firstName: "Susy",
		lastName: "Fong",
	},
	{
		status: "B",
		membershipNumber: "1018",
		firstName: "Anouk",
		lastName: "Frolic",
	},
	{
		status: "D",
		membershipNumber: "1018",
		firstName: "Adam",
		lastName: "Frolic",
	},
	{
		status: "A",
		membershipNumber: "1021",
		firstName: "Kate",
		lastName: "Wilson",
	},
	{
		status: "B",
		membershipNumber: "1021",
		firstName: "Don",
		lastName: "Vermeer",
	},
	{
		status: "D",
		membershipNumber: "1024",
		firstName: "Kate",
		lastName: "George",
	},
	{
		status: "A",
		membershipNumber: "1025",
		firstName: "J.Eduardo",
		lastName: "Pereira",
	},
	{
		status: "B",
		membershipNumber: "1025",
		firstName: "Marc",
		lastName: "Feifer",
	},
	{
		status: "C",
		membershipNumber: "1025",
		firstName: "Art",
		lastName: "de Guzman",
	},
	{
		status: "A",
		membershipNumber: "1026",
		firstName: "Kean P.",
		lastName: "Moynihan",
	},
	{
		status: "B",
		membershipNumber: "1026",
		firstName: "William",
		lastName: "Moynihan",
	},
	{
		status: "A",
		membershipNumber: "1027",
		firstName: "Rufus",
		lastName: "Wilkes",
	},
	{
		status: "E",
		membershipNumber: "1027",
		firstName: "Lila",
		lastName: "Train",
	},
	{
		status: "A",
		membershipNumber: "1028",
		firstName: "Edward R.",
		lastName: "Snoyer",
	},
	{
		status: "B",
		membershipNumber: "1028",
		firstName: "Ros-Marie",
		lastName: "Snoyer",
	},
	{
		status: "A",
		membershipNumber: "1031",
		firstName: "Marc",
		lastName: "Davies",
	},
	{
		status: "A",
		membershipNumber: "1033",
		firstName: "Scott",
		lastName: "Jones",
	},
	{
		status: "B",
		membershipNumber: "1033",
		firstName: "Heather",
		lastName: "Jones",
	},
	{
		status: "A",
		membershipNumber: "1035",
		firstName: "Tim",
		lastName: "Kirkwood",
	},
	{
		status: "B",
		membershipNumber: "1035",
		firstName: "Valentia",
		lastName: "Kirkwood",
	},
	{
		status: "A",
		membershipNumber: "1037",
		firstName: "Alison",
		lastName: "Barlow",
	},
	{
		status: "B",
		membershipNumber: "1037",
		firstName: "John",
		lastName: "Toews",
	},
	{
		status: "E",
		membershipNumber: "1038",
		firstName: "Brent",
		lastName: "Abdool",
	},
	{
		status: "E",
		membershipNumber: "1038",
		firstName: "Neisha",
		lastName: "Singh",
	},
	{
		status: "E",
		membershipNumber: "1040",
		firstName: "Chris",
		lastName: "Ruttan",
	},
	{
		status: "E",
		membershipNumber: "1040",
		firstName: "Noelle",
		lastName: "Rancourt",
	},
	{
		status: "A",
		membershipNumber: "1043",
		firstName: "Marcus",
		lastName: "Van Ierssel",
	},
	{
		status: "B",
		membershipNumber: "1043",
		firstName: "Jennifer",
		lastName: "van Ierrssel",
	},
	{
		status: "A",
		membershipNumber: "1044",
		firstName: "Frederick",
		lastName: "Kent",
	},
	{
		status: "B",
		membershipNumber: "1044",
		firstName: "Celina",
		lastName: "Grebski",
	},
	{
		status: "A",
		membershipNumber: "1045",
		firstName: "Chris",
		lastName: "Speed",
	},
	{
		status: "B",
		membershipNumber: "1045",
		firstName: "Pamela",
		lastName: "Speed",
	},
	{
		status: "A",
		membershipNumber: "1046",
		firstName: "Bjorn",
		lastName: "Pettersson",
	},
	{
		status: "A",
		membershipNumber: "1047",
		firstName: "Adam",
		lastName: "Walkowiak",
	},
	{
		status: "B",
		membershipNumber: "1047",
		firstName: "Marzena",
		lastName: "Walkowiak",
	},
	{
		status: "A",
		membershipNumber: "1048",
		firstName: "Keith",
		lastName: "Bohlender",
	},
	{
		status: "B",
		membershipNumber: "1048",
		firstName: "Marie",
		lastName: "Gallo-Bohlender",
	},
	{
		status: "A",
		membershipNumber: "1053",
		firstName: "Barna",
		lastName: "Moricz",
	},
	{
		status: "B",
		membershipNumber: "1053",
		firstName: "Audrey",
		lastName: "Lupke",
	},
	{
		status: "B",
		membershipNumber: "1054",
		firstName: "Beth",
		lastName: "Hickman",
	},
	{
		status: "D",
		membershipNumber: "1054",
		firstName: "Robert",
		lastName: "Hickman",
	},
	{
		status: "A",
		membershipNumber: "1055",
		firstName: "Bill",
		lastName: "Miller",
	},
	{
		status: "E",
		membershipNumber: "1055",
		firstName: "Ejay",
		lastName: "Russel",
	},
	{
		status: "A",
		membershipNumber: "1057",
		firstName: "Rafal",
		lastName: "Bilyk",
	},
	{
		status: "B",
		membershipNumber: "1057",
		firstName: "Paulina",
		lastName: "Brozyna",
	},
	{
		status: "A",
		membershipNumber: "1060",
		firstName: "Harry",
		lastName: "Minaker",
	},
	{
		status: "E",
		membershipNumber: "1063",
		firstName: "Meital",
		lastName: "Tietz",
	},
	{
		status: "E",
		membershipNumber: "1063",
		firstName: "Shevah Jeff",
		lastName: "Tietz",
	},
	{
		status: "E",
		membershipNumber: "1065",
		firstName: "Ben",
		lastName: "Gondek",
	},
	{
		status: "E",
		membershipNumber: "1065",
		firstName: "Michael",
		lastName: "Gondek",
	},
	{
		status: "L",
		membershipNumber: "1066",
		firstName: "Fred",
		lastName: "Nicolaidis",
	},
	{
		status: "L",
		membershipNumber: "1066",
		firstName: "Wendy",
		lastName: "Nicolaidis",
	},
	{
		status: "E",
		membershipNumber: "1067",
		firstName: "Wayne",
		lastName: "Logan",
	},
	{
		status: "A",
		membershipNumber: "1069",
		firstName: "Jozef",
		lastName: "Husar",
	},
	{
		status: "B",
		membershipNumber: "1069",
		firstName: "Margaret",
		lastName: "Hussar",
	},
	{
		status: "A",
		membershipNumber: "1070",
		firstName: "Cathryn",
		lastName: "MacFarlane",
	},
	{
		status: "B",
		membershipNumber: "1070",
		firstName: "Paul",
		lastName: "Scott",
	},
	{
		status: "A",
		membershipNumber: "1071",
		firstName: "Boris Alexandre",
		lastName: "Sucharov",
	},
	{
		status: "B",
		membershipNumber: "1071",
		firstName: "Luciana",
		lastName: "Pache de Faria",
	},
	{
		status: "B",
		membershipNumber: "1073",
		firstName: "Carol",
		lastName: "Wilson",
	},
	{
		status: "D",
		membershipNumber: "1073",
		firstName: "Jim",
		lastName: "Wilson",
	},
	{
		status: "A",
		membershipNumber: "1074",
		firstName: "Alexei",
		lastName: "Pachkevitch",
	},
	{
		status: "B",
		membershipNumber: "1074",
		firstName: "Elena",
		lastName: "Pachkevitch",
	},
	{
		status: "A",
		membershipNumber: "1077",
		firstName: "Jeff",
		lastName: "Willis",
	},
	{
		status: "B",
		membershipNumber: "1077",
		firstName: "Gabriele",
		lastName: "Muekusch",
	},
	{
		status: "A",
		membershipNumber: "1078",
		firstName: "Dominik",
		lastName: "Gawron",
	},
	{
		status: "A",
		membershipNumber: "1082",
		firstName: "Timon",
		lastName: "Orawski",
	},
	{
		status: "B",
		membershipNumber: "1082",
		firstName: "Sonia",
		lastName: "Satov",
	},
	{
		status: "A",
		membershipNumber: "1083",
		firstName: "Brian",
		lastName: "Burchell",
	},
	{
		status: "B",
		membershipNumber: "1083",
		firstName: "Lisa",
		lastName: "Lomax",
	},
	{
		status: "A",
		membershipNumber: "1085",
		firstName: "Gregory",
		lastName: "Graham",
	},
	{
		status: "B",
		membershipNumber: "1085",
		firstName: "Judith",
		lastName: "MacDonald",
	},
	{
		status: "A",
		membershipNumber: "1087",
		firstName: "John K.",
		lastName: "Hunter",
	},
	{
		status: "B",
		membershipNumber: "1087",
		firstName: "Lois",
		lastName: "Hunter",
	},
	{
		status: "A",
		membershipNumber: "1090",
		firstName: "James",
		lastName: "Roscoe",
	},
	{
		status: "B",
		membershipNumber: "1090",
		firstName: "Melanie",
		lastName: "Roscoe",
	},
	{
		status: "B",
		membershipNumber: "1091",
		firstName: "Ellie",
		lastName: "Myers",
	},
	{
		status: "D",
		membershipNumber: "1091",
		firstName: "Jerrett",
		lastName: "Myers",
	},
	{
		status: "A",
		membershipNumber: "1092",
		firstName: "John",
		lastName: "Ross",
	},
	{
		status: "B",
		membershipNumber: "1092",
		firstName: "Maia",
		lastName: "Onno",
	},
	{
		status: "B",
		membershipNumber: "1093",
		firstName: "Petr",
		lastName: "Jano",
	},
	{
		status: "D",
		membershipNumber: "1093",
		firstName: "Christine",
		lastName: "Rodway",
	},
	{
		status: "A",
		membershipNumber: "1094",
		firstName: "Tom",
		lastName: "Majcherczyk",
	},
	{
		status: "B",
		membershipNumber: "1094",
		firstName: "Cristina",
		lastName: "Delago",
	},
	{
		status: "A",
		membershipNumber: "1095",
		firstName: "Mike",
		lastName: "Rossiter",
	},
	{
		status: "B",
		membershipNumber: "1095",
		firstName: "Lauren",
		lastName: "Dixon",
	},
	{
		status: "A",
		membershipNumber: "1096",
		firstName: "John",
		lastName: "Komac",
	},
	{
		status: "A",
		membershipNumber: "1099",
		firstName: "Jason",
		lastName: "Kahng",
	},
	{
		status: "A",
		membershipNumber: "1100",
		firstName: "Slawomir (Slav)",
		lastName: "Domurat",
	},
	{
		status: "B",
		membershipNumber: "1100",
		firstName: "Stephanie",
		lastName: "Domurat",
	},
	{
		status: "E",
		membershipNumber: "1101",
		firstName: "David",
		lastName: "Dickey",
	},
	{
		status: "D",
		membershipNumber: "1103",
		firstName: "Newman",
		lastName: "Mallon",
	},
	{
		status: "B",
		membershipNumber: "1104",
		firstName: "Darragh",
		lastName: "Purcell",
	},
	{
		status: "D",
		membershipNumber: "1104",
		firstName: "Larry",
		lastName: "Purcell",
	},
	{
		status: "B",
		membershipNumber: "1105",
		firstName: "Frances (Nicki)",
		lastName: "Anger",
	},
	{
		status: "D",
		membershipNumber: "1105",
		firstName: "Adam",
		lastName: "Morin",
	},
	{
		status: "B",
		membershipNumber: "1108",
		firstName: "Lydia",
		lastName: "Gilbert",
	},
	{
		status: "D",
		membershipNumber: "1108",
		firstName: "Paul",
		lastName: "Willis",
	},
	{
		status: "D",
		membershipNumber: "1112",
		firstName: "Trevor",
		lastName: "Leech",
	},
	{
		status: "E",
		membershipNumber: "1113",
		firstName: "Chantal",
		lastName: "Regimbal",
	},
	{
		status: "E",
		membershipNumber: "1113",
		firstName: "David",
		lastName: "Todd",
	},
	{
		status: "B",
		membershipNumber: "1114",
		firstName: "Yulia",
		lastName: "Lachakov",
	},
	{
		status: "D",
		membershipNumber: "1114",
		firstName: "Alexander",
		lastName: "Gangurean",
	},
	{
		status: "D",
		membershipNumber: "1115",
		firstName: "John",
		lastName: "Yi Gong",
	},
	{
		status: "D",
		membershipNumber: "1116",
		firstName: "Brendan",
		lastName: "Ruck",
	},
	{
		status: "A",
		membershipNumber: "1117",
		firstName: "Jack",
		lastName: "Willoughby",
	},
	{
		status: "A",
		membershipNumber: "1118",
		firstName: "Mike",
		lastName: "Chmura",
	},
	{
		status: "B",
		membershipNumber: "1118",
		firstName: "Beata",
		lastName: "Szwoger-Lettecki",
	},
	{
		status: "E",
		membershipNumber: "1119",
		firstName: "Miomir",
		lastName: "Koledin",
	},
	{
		status: "E",
		membershipNumber: "1119",
		firstName: "William",
		lastName: "Koledin",
	},
	{
		status: "A",
		membershipNumber: "1120",
		firstName: "Michelle",
		lastName: "Robidoux",
	},
	{
		status: "B",
		membershipNumber: "1120",
		firstName: "Christine",
		lastName: "Beckerman",
	},
	{
		status: "A",
		membershipNumber: "1121",
		firstName: "Peter",
		lastName: "Weninger",
	},
	{
		status: "A",
		membershipNumber: "1122",
		firstName: "Jeffrey",
		lastName: "James",
	},
	{
		status: "B",
		membershipNumber: "1122",
		firstName: "Kate",
		lastName: "McCormick",
	},
	{
		status: "A",
		membershipNumber: "1123",
		firstName: "Graham",
		lastName: "Reid",
	},
	{
		status: "A",
		membershipNumber: "1124",
		firstName: "Vincent",
		lastName: "Grossi",
	},
	{
		status: "A",
		membershipNumber: "1125",
		firstName: "Jaime",
		lastName: "Restrepo",
	},
	{
		status: "E",
		membershipNumber: "1126",
		firstName: "John",
		lastName: "Haig",
	},
	{
		status: "A",
		membershipNumber: "1127",
		firstName: "Mark",
		lastName: "Lewiecki",
	},
	{
		status: "B",
		membershipNumber: "1127",
		firstName: "Sophia",
		lastName: "Lilly",
	},
	{
		status: "A",
		membershipNumber: "1128",
		firstName: "Nicholas",
		lastName: "Scribner",
	},
	{
		status: "B",
		membershipNumber: "1128",
		firstName: "Katalin",
		lastName: "Ruza",
	},
	{
		status: "B",
		membershipNumber: "1129",
		firstName: "Jean",
		lastName: "Wright",
	},
	{
		status: "C",
		membershipNumber: "1129",
		firstName: "Jaan",
		lastName: "Luts",
	},
	{
		status: "C",
		membershipNumber: "1130",
		firstName: "Carole",
		lastName: "Enriquez",
	},
	{
		status: "E",
		membershipNumber: "1131",
		firstName: "Tim",
		lastName: "Knight",
	},
	{
		status: "E",
		membershipNumber: "1132",
		firstName: "Damman",
		lastName: "Zanemla",
	},
	{
		status: "C",
		membershipNumber: "1133",
		firstName: "Anna",
		lastName: "Pachkevitch",
	},
	{
		status: "E",
		membershipNumber: "1134",
		firstName: "Kevin",
		lastName: "Loughborough",
	},
	{
		status: "A",
		membershipNumber: "1135",
		firstName: "Antonio",
		lastName: "Rebelo",
	},
	{
		status: "B",
		membershipNumber: "1135",
		firstName: "Grace",
		lastName: "Rebelo",
	},
	{
		status: "B",
		membershipNumber: "1136",
		firstName: "Meghan",
		lastName: "Siddall",
	},
	{
		status: "E",
		membershipNumber: "1136",
		firstName: "Michael",
		lastName: "Wilson",
	},
	{
		status: "A",
		membershipNumber: "1137",
		firstName: "Katie",
		lastName: "Grundy",
	},
	{
		status: "A",
		membershipNumber: "1138",
		firstName: "Frederic",
		lastName: "Chevalier",
	},
	{
		status: "B",
		membershipNumber: "1138",
		firstName: "Isabelle",
		lastName: "Poirier",
	},
	{
		status: "B",
		membershipNumber: "1139",
		firstName: "James",
		lastName: "Sutcliffe",
	},
	{
		status: "C",
		membershipNumber: "1139",
		firstName: "Katina",
		lastName: "Sutcliffe",
	},
	{
		status: "A",
		membershipNumber: "1140",
		firstName: "Carol",
		lastName: "McFarlane",
	},
	{
		status: "A",
		membershipNumber: "1141",
		firstName: "Janaya",
		lastName: "Letkeman",
	},
	{
		status: "B",
		membershipNumber: "1141",
		firstName: "Robert",
		lastName: "Froese",
	},
	{
		status: "B",
		membershipNumber: "1142",
		firstName: "Alison",
		lastName: "McIntyre",
	},
	{
		status: "A",
		membershipNumber: "1143",
		firstName: "Graham",
		lastName: "Merry",
	},
	{
		status: "B",
		membershipNumber: "1143",
		firstName: "Christine",
		lastName: "Lee",
	},
	{
		status: "A",
		membershipNumber: "1144",
		firstName: "Daniel",
		lastName: "Mingorance-Geraldo",
	},
	{
		status: "A",
		membershipNumber: "1145",
		firstName: "Marc",
		lastName: "Grossi",
	},
	{
		status: "A",
		membershipNumber: "1146",
		firstName: "Daniel",
		lastName: "Aufgang",
	},
	{
		status: "C",
		membershipNumber: "1147",
		firstName: "Joel",
		lastName: "Aufgang",
	},
	{
		status: "A",
		membershipNumber: "1148",
		firstName: "Soren",
		lastName: "Hesse",
	},
	{
		status: "A",
		membershipNumber: "1149",
		firstName: "John",
		lastName: "Gunel",
	},
	{
		status: "A",
		membershipNumber: "1150",
		firstName: "Andrew",
		lastName: "White",
	},
	{
		status: "A",
		membershipNumber: "1151",
		firstName: "Adam",
		lastName: "Melanson",
	},
	{
		status: "A",
		membershipNumber: "1152",
		firstName: "Yu Charlie",
		lastName: "Yang",
	},
	{
		status: "E",
		membershipNumber: "1153",
		firstName: "Bill",
		lastName: "Hutton",
	},
	{
		status: "A",
		membershipNumber: "1154",
		firstName: "Eileen",
		lastName: "Taylor",
	},
	{
		status: "D",
		membershipNumber: "1155",
		firstName: "Aidan",
		lastName: "Birch",
	},
	{
		status: "A",
		membershipNumber: "1156",
		firstName: "Brian",
		lastName: "Cooper",
	},
	{
		status: "A",
		membershipNumber: "1157",
		firstName: "Dominic",
		lastName: "Ewenson",
	},
	{
		status: "A",
		membershipNumber: "1158",
		firstName: "Alex",
		lastName: "Bartlett",
	},
	{
		status: "A",
		membershipNumber: "1159",
		firstName: "Jaroslaw",
		lastName: "Niedbala",
	},
	{
		status: "A",
		membershipNumber: "1160",
		firstName: "Katherine",
		lastName: "Lilley",
	},
	{
		status: "A",
		membershipNumber: "1162",
		firstName: "Evert",
		lastName: "Steenge",
	},
	{
		status: "F",
		membershipNumber: "1163",
		firstName: "Timothy",
		lastName: "Maguire",
	},
	{
		status: "A",
		membershipNumber: "1168",
		firstName: "Gordon",
		lastName: "Gilbert",
	},
	{
		status: "C",
		membershipNumber: "1169",
		firstName: "Farhad",
		lastName: "Mushfiq",
	},
	{
		status: "C",
		membershipNumber: "1169",
		firstName: "Liaqat",
		lastName: "Ali",
	},
	{
		status: "C",
		membershipNumber: "1169",
		firstName: "Showkat",
		lastName: "Ali",
	},
	{
		status: "F",
		membershipNumber: "1170",
		firstName: "Jason",
		lastName: "Rude",
	},
]
